server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/leonardosantino/config-repo

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health
info:
  app:
    name: Config Server
    description: Spring Cloud Config Server Application
    version: 1.0.0